trigger: none

pool:
  vmImage: 'windows-2022'

variables:
  arch: 'x64'
  configuration: 'Release'
  artifact: 'BravoStore-$(arch)'
  major: 1
  minor: 0
  build: 0

steps:
- task: UseDotNet@2
  displayName: 'Use .NET 5.0 SDK'
  inputs:
    packageType: sdk
    version: 5.0.x
- task: DotNetCoreCLI@2
  displayName: '.NET restore'
  inputs:
    command: 'restore'
    projects: 'src\Bravo.csproj'
    feedsToUse: 'select'
    verbosityRestore: 'Normal'
- task: PowerShell@2
  displayName: "Update appxmanifest version"
  inputs:
    targetType: 'inline'
    script: |
      $version = "$(major).$(minor).$(build).0"
      Write-Host "Updating to version [$version]"
      [xml]$manifest = Get-Content ".\Package.appxmanifest"
      $manifest.Package.Identity.Version = "$version"
      $manifest.Save("./Package.appxmanifest")
    warningPreference: 'stop'
    failOnStderr: true
    showWarnings: true
    workingDirectory: '$(Build.SourcesDirectory)\installer\msix\Bravo.Installer.Msix'
- task: MSBuild@1
  displayName: "MSBuild MSIX"
  inputs:
    solution: 'installer/msix/Bravo.Installer.Msix/Bravo.Installer.Msix.wapproj'
    platform: '$(arch)'
    configuration: '$(configuration)'
    msbuildArguments: '
      /p:UapAppxPackageBuildMode=SideLoadOnly 
      /p:AppxBundle=Never
      /p:AppxPackageOutput=$(Build.ArtifactStagingDirectory)\$(artifact).msix 
      /p:AppxPackageSigningEnabled=false'
    clean: true
- task: DotNetCoreCLI@2
  displayName: 'Install AzureSignTool'
  inputs:
    command: 'custom'
    custom: 'tool'
    arguments: 'update --global azuresigntool'
- task: CmdLine@2
  displayName: 'Code signing MSIX'
  inputs:
    script: 'AzureSignTool sign -kvu "$(SigningVaultURL)" -kvt "$(SigningTenantId)" -kvi "$(SigningClientId)" -kvs "$(SigningClientSecret)" -kvc "$(SigningCertName)" -tr http://timestamp.digicert.com -v "$(Build.ArtifactStagingDirectory)\$(artifact).msix"'
    failOnStderr: true
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'
